Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: xyz.rohan.App
      CodeUri: G:\Programs\IntelliJ\aws-maven\face-compare
      Runtime: java8.al2